### ISSUE TITLE
sfdx shane:object:fields:describe only returns system default fields

### ISSUE THREAD

**Issue by mitchconquer** [mshanemc/shane-sfdx-plugins#10]
Hi I wonder if I'm doing something incorrectly but whenever I run `sfdx shane:object:fields:describe -o My_Object__c` I only get the default system fields in the result but no custom fields. Is there a way to see custom fields?

**Comment by mitchconquer** [comment]
Oh tehehe seems to be the fields weren't visible 😬

**Comment by mshanemc** [comment]
like permissions? @mitchconquer
