### ISSUE TITLE
Errors installing: incompatible module?

### ISSUE THREAD

**Issue by camisotro** [mshanemc/shane-sfdx-plugins#16]
I'm attempting to install via `sfdx plugins:Install shane-sfdx-plugins`. I have npm 6.5.0 and node 10.15.0 installed.

Result:

```
Finished digital signature check. Installing... !
 !    yarn --non-interactive --mutex=file:C:\Users\(omitted)\AppData\Local\sfdx\yarn --cache-folder=C:\Users\Charles.Troster\AppData\Local\sfdx\yarn exited with code 1
 !    warning shane-sfdx-plugins > npm > npm-registry-fetch@1.1.1: this version has a breaking change. use 1.1.0 or upgrade to latest
 !    warning shane-sfdx-plugins > npm > npm-registry-fetch > make-fetch-happen > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug
 !    with socket data flow and an import issue introduced in 2.1.0
 !    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi@6.10.1: This version is no longer maintained. Please upgrade to the latest version.
 !    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
 !    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi > topo@1.1.0: This version is no longer maintained. Please upgrade to the latest version.
 !    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > nise > text-encoding@0.6.4: no longer maintained
 !    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of
 !    @sinonjs/samsam
 !    error shane-sfdx-plugins@1.1.1: The engine "node" is incompatible with this module. Expected version ">=10.15.0".
 !    error Found incompatible module
 !
```
I got this error once, upgraded node to current, and now am still getting the same error. Any thoughts?

**Comment by mshanemc** [comment]
current LTS is 10.15.0 (which is why I left it there) and current is 11.6.0 (what I'm running).

I took out sinon (it's only for testing anyway...not sure why that's needed in a package).

Can you try that and see if it works for you now?

**Comment by mshanemc** [comment]
I did a full uninstall from local and the re-install from the published package, and it worked fine.

**Comment by camisotro** [comment]
I tried an uninstall but it just said not installed.

Tried the install and I'm getting exactly the same messages. Including the ones about sinon. 

I am still baffled by **The engine "node" is incompatible with this module. Expected version ">=10.15.0".** even though I have exactly 10.15.0 installed.

**Comment by mshanemc** [comment]
well, crap.  looks like that sinon use isn't mine, but coming from sfdx core.

Can you try updating node to 11.6 to check?

**Comment by camisotro** [comment]
I was intending to stick with the LTS version so I'm not on the bleeding edge.

It seems like the "warnings" are not actually what breaks it, only the errors. I just don't understand why it's telling me "node" is not new enough. Unless sfdx has some older internal version of node that it's using?

I also tried updating sfdx itself. It's up to 6.48.0-bfccc40118 now. Same errors.

**Comment by camisotro** [comment]
I think I have a culprit... the version of Node located at C:\Users\(my username)\AppData\Local\sfdx\client\bin is version 8.9.4. This one would have been installed by SFDX itself. If I rename that one and replace it with node.exe 10.15.0 the error goes away.

So it seems the right minimum version of node for a plugin to target is whatever version SFDX is installing?

**Comment by thhsfdc** [comment]
trying to install this on MacOS Mojave 10.14.2 (18C54) with a similar error:

`sfdx plugins:install shane-sfdx-plugins
Installing plugin shane-sfdx-plugins...
Installing plugin shane-sfdx-plugins... Checking for digital signature.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check. Installing... !
 ▸    yarn --non-interactive --mutex=file:/Users/thoeger/Library/Caches/sfdx/yarn --cache-folder=/Users/thoeger/Library/Caches/sfdx/yarn exited with code 1
 ▸    warning shane-sfdx-plugins > npm > npm-registry-fetch@1.1.1: this version has a breaking change. use 1.1.0 or upgrade to latest
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi@6.10.1: This version is no longer maintained. Please upgrade to the latest version.
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi > topo@1.1.0: This version is no longer maintained. Please upgrade to the latest version.
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
 ▸    warning shane-sfdx-plugins > npm > npm-registry-fetch > make-fetch-happen > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with
 ▸    socket data flow and an import issue introduced in 2.1.0
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > nise > text-encoding@0.6.4: no longer maintained
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of
 ▸    @sinonjs/samsam
 ▸    error shane-sfdx-plugins@1.1.2: The engine "node" is incompatible with this module. Expected version ">=10.15.0".
 ▸    error Found incompatible module
 ▸    
`

whilst Homebrew confirms` node 11.6.0 already installed` and also `socks-proxy-agent@4.0.1
`

So ... kind of stuck :-( 

Any ideas out here?

**Comment by camisotro** [comment]
@thhsfdc It seems that the plugin install does not execute the version of node you have installed, but rather the internal version that gets installed by SFDX. And that version is below 10.15.0.

**Comment by mshanemc** [comment]
1. make sure sfdx update has run so that you've got the latest core/plugins
2. I've been using the pre-release version the sfdx plugin, so that may be why I can't replicate your issue.

You could try that using the instructions here, https://www.npmjs.com/package/salesforcedx, then try my plugin, then go back to @latest to get back to how it was.

Sorry for all the pain.

**Comment by jdgirald** [comment]
1. install via npm globally
2. sfdx plugins:link [path to node package]

**Comment by idanblich** [comment]
+1
`node -v` : v11.8.0
`npm -v`  : 6.7.0
I also uninstall and reinstall sfdx 
`sfdx -v`  :sfdx-cli/6.50.0-9817aece8a (darwin-x64) node-v8.9.4
```
 sfdx plugins:install shane-sfdx-plugins


Installing plugin shane-sfdx-plugins...
Installing plugin shane-sfdx-plugins... Checking for digital signature.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check. Installing... !
 ▸    yarn --non-interactive --mutex=file:/Users/idan/Library/Caches/sfdx/yarn --cache-folder=/Users/idan/Library/Caches/sfdx/yarn exited with code 1
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > nise > text-encoding@0.6.4: no longer maintained
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of
 ▸    @sinonjs/samsam
 ▸    error shane-sfdx-plugins@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.15.0".
 ▸    error Found incompatible module
 ▸    
```

**Comment by mshanemc** [comment]
Can someone who still has this node engine problem try the latest release (2.1.0)?

I talked some someone from the sfdx cli team, and they're eventually going to move to LTS node but it's not going to be quick.  I'm hoping that by not specifying an engine, npm just kinda sorts it out for you.

@idanblich @thhsfdc

**Comment by idanblich** [comment]
Working ! 
Thank you  @mshanemc  
```
sfdx plugins:install shane-sfdx-plugins


Installing plugin shane-sfdx-plugins...
Installing plugin shane-sfdx-plugins... Checking for digital signature.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check. Installing... done
```

**Comment by thhsfdc** [comment]
Great - that works now straight forward :-)
$sfdx plugins
shane-sfdx-plugins 2.1.0
