### ISSUE TITLE
Issue trying to install version 3.2.0

### ISSUE THREAD

**Issue by AltiusRupert** [mshanemc/shane-sfdx-plugins#22]
```
~ $ sfdx plugins:install shane-sfdx-plugins
Installing plugin shane-sfdx-plugins...
Installing plugin shane-sfdx-plugins... Checking for digital signature.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check. Installing... !
 ▸    yarn --non-interactive --mutex=file:/app/.cache/sfdx/yarn --cache-folder=/app/.cache/sfdx/yarn exited with code 1
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi@6.10.1: This version is no longer maintained. Please upgrade to the latest version.
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi > topo@1.1.0: This version is no longer maintained. Please upgrade to the latest version.
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > jsonwebtoken > joi > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
 ▸    warning shane-sfdx-plugins > @salesforce/command > @salesforce/core > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been deprecated in favour of
 ▸    @sinonjs/samsam
 ▸    error natural-orderby@1.1.1: The engine "node" is incompatible with this module. Expected version "^8.10.0 || >=9.10.0".
 ▸    error Found incompatible module
 ▸    
Finished digital signature check. Installing... done
~ $ node -v
v10.15.2
~ $ 
```

**Comment by mshanemc** [comment]
cross-linked to what I think is related the problem with the latest oclif version

https://github.com/oclif/dev-cli/issues/90

**Comment by mshanemc** [comment]
from what I've heard from other people, sfdx is maybe selecting a node version for you instead of using what you have installed locally (the result of node-v).

**Comment by AltiusRupert** [comment]
Hmmm. I will try to hard-code the path to bin/sfdx
Is there a way to revert to your plugin version 3.1.0 ?

**Comment by AltiusRupert** [comment]
This is useful for me : at least once I have a stable configuration, it will help me keep it that way :
"Disable Automatic Update of the CLI and Plug-In"
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm#sfdx_setup_install_plugin_version

**Comment by camisotro** [comment]
On Windows there is a copy of node.exe at C:\Users\Charles\AppData\Local\sfdx\client\bin and this is the one that gets executed by sfdx. It is presently version 8.9.4. I bypassed this error by replacing this with a newer version node.exe which hopefully won't break anything.

**Comment by AltiusRupert** [comment]
@camisotro Interesting !
But I'm not sure it's a Node version problem, rather an OCLIF issue.  

I got a message from @WadeWegner sayong the problem in Salesforce CLI would be fixed by Thursday 7-march 
https://twitter.com/WadeWegner/status/1101899612485369857

**Comment by AltiusRupert** [comment]
This issue was fixed with latest version of SFDX :
sfdx-cli/6.56.0-e3fd846a1f (darwin-x64) node-v8.15.1

**Comment by mshanemc** [comment]
that's great, thanks for the update @AltiusRupert.  Sometimes the dependencies down the stack give back what they take away.
