### ISSUE TITLE
"shane:mdapi:pull" fails on metadata with single folder. Error "folderListMetadata is not iterable"

### ISSUE THREAD

**Issue by arbackhouse** [mshanemc/shane-sfdx-plugins#23]
When running `shane:mdapi:pull`, if the metadata requested is in a folder and there is only one folder of that type present in the org, the command fails with the error `folderListMetadata is not iterable`.  

It appears that at https://github.com/mshanemc/shane-sfdx-plugins/blob/26eb146ee06bda751de3cfed5a7a11e1d443b98d/src/commands/shane/mdapi/pull.ts#L114 if there is only a single folder, `folderListMetadata` is an object rather than an array. In my case it was EmailTemplate in an org with only the `unfiled$public` folder.

**Comment by mshanemc** [comment]
thanks for reporting @arbackhouse .  Patched in 3.2.4.

I would love to see that quirk get fixed in the underlying jsforce implementation of metadata (always return arrays for metadata.list)
