### ISSUE TITLE
🐛 PermissionSet converted from Profile has invalid visibility tab settings

### ISSUE THREAD

**Issue by e02d96ec16** [mshanemc/shane-sfdx-plugins#26]
1. Acquire some Profile e.g. the Admin.profile SFDX seems to always generate
1. Convert Profile to PermissionSet: `sfdx shane:profile:convert -n Administrator -p Admin`
1. Deploy: `sfdx force:source:push -f -g -w 30`
1. 💥
> Error parsing file: 'Hidden' is not a valid value for the enum 'PermissionSetTabVisibility'

Line pointed to:
```diff
+    <tabSettings>
+        <tab>Example__c</tab>
-        <visibility>Hidden</visibility>
+    </tabSettings>
```
`DefaultOn` was another invalid visibility.
[Docs says](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_permissionset.htm) these are not valid values _at all_:
![image](https://user-images.githubusercontent.com/14942417/54621844-5c750700-4a60-11e9-8981-e9bbaad75868.png)
Manually changing the visibilities to e.g. `Visible` made it possible to deploy again.

**Comment by mshanemc** [comment]
@e02d96ec16 thanks for a super well-crafted issue.  

I **think** I fixed it.  Since you've got an org with the issue, can you `sfdx update` and check out the latest version for me?

**Comment by e02d96ec16** [comment]
@mshanemc Confirmed. Thank you very much!
