### ISSUE TITLE
ERROR running GithubPackageInstall:  404 - {"error":"Not Found"} 

### ISSUE THREAD

**Issue by afawcett** [mshanemc/shane-sfdx-plugins#3]
I am trying the following 

sfdx shane:github:package:install -g afawcett -r custommetadataapi

**Comment by afawcett** [comment]
Looks like the URL its constructing is not valid maybe?

**Comment by mshanemc** [comment]
Yep, thanks!  just patched as 0.14.1 (as well as updating some of the
internals, like using --package instead of -i on packageInstall.

Sorry about that.
