### ISSUE TITLE
Mismatched version warning

### ISSUE THREAD

**Issue by hotcher2** [mshanemc/shane-sfdx-plugins#30]
Thoughts on why I am receiving this warning?

![image](https://user-images.githubusercontent.com/35346734/55006710-2e397f00-4fac-11e9-816c-ccada92b1411.png)

**Comment by mshanemc** [comment]
weird...did you install via sfdx plugins:install or link from source?

Current version *should* be 3.5.0...may try uninstall->reinstall?
