### ISSUE TITLE
Feature Request: Communities:Publish --all

### ISSUE THREAD

**Issue by aheber** [mshanemc/shane-sfdx-plugins#43]
Wanted to post here before I built a merge request.

I would love to have an `--all` flag on the Communities Publish. At the end of spinning up a new Scratch Org we are publishing all of the true communities. 

Right now we're doing it with a script
1. Get list of communities eligible for publishing
`select id, Name, status, UrlPathPrefix, OptionsSiteAsContainerEnabled from Network WHERE OptionsSiteAsContainerEnabled = true`
2. Loop through each community and publish

I'm happy to send an MR but wanted to talk about how you might want to do the parameters on this. You currently have `name` as a required argument, should that become a non-required argument with another flag added for `--all,-a`?
Would you rather handle this differently?

Thanks for your wonderful set of commands.

**Comment by mshanemc** [comment]
I like that idea.  

Probably we could make the name optional, and have communities:publish do them all by default.  

Then, if you specify a name, it has to be found and then it’ll publish just that.

If you want to PR it, go ahead.  Otherwise I’ll probably get to it within a few weeks.

**Comment by aheber** [comment]
That sounds like a good way to go. I'll plan to send a PR for it, should be able to find some time this weekend.

**Comment by mshanemc** [comment]
added in 3.21
