### ISSUE TITLE
Convert Profile to Permissionset and remove rights from Profile - Profile still contains all rights 

### ISSUE THREAD

**Issue by stoevie** [mshanemc/shane-sfdx-plugins#50]
I want to create an minimized Admin profile and put all field and object permissions in a permissionset.

After I clone the Admin profile (SystemAdminMinimum), pull the cloned profile into VS code, run sfdx shane:profile:convert -p SystemAdminMinimum -n PrfMinimumAdmin -e and push the minimized profile back to my scratch org, the profile still contains all field and object permissions on all objects. Am I doing something wrong?

**Comment by mshanemc** [comment]
1. does the profile still have all the perms in local source?
2. if you push to a new scratch org, does the profile still have all the perms?

**Comment by bwong70** [comment]
If the profile has "Modify All Data" and/or "View All Data", the object
permissions are automatically injected so you must remove both of these
user permissions first.

**Comment by mshanemc** [comment]
thanks for the input, @bwong70!  Learn something new all the time.

@stoevie so I guess it would it make sense to have the -e branch of this command remove those things from the profile if they exist already?

**Comment by stoevie** [comment]
@mshanemc, sorry for my late response, I was on vacation.
Yes, It make sense to remove these permissions first.
