### ISSUE TITLE
Enhancement request : more detailed descriptions in README

### ISSUE THREAD

**Issue by AltiusRupert** [mshanemc/shane-sfdx-plugins#6]
Hi Shane,
This plugin is enormous, thanks a lot !

The README is very detailed and very understandable ... for someone who has already used each option and who wishes to go into more detail.

However, the one-liner description of each command si rather short and not always self-explanatory for someone who is discovering your plugin, SFDX, and who has never used it.

Would it be possible to give a more detailed description of each command ?

Thanks,
Rupert

**Comment by mshanemc** [comment]
hey @AltiusRupert.   The README is auto-generated from the cli's help text.  Which commands' summary do you think need more details?
