### ISSUE TITLE
sfdx shane:mdapi:pull - Returning Object.keys(...).map(...).flat is not a function

### ISSUE THREAD

**Issue by ronyaoun** [mshanemc/shane-sfdx-plugins#68]
When running the command sfdx shane:mdapi:pull, it now returns 
ERROR running shane:mdapi:pull:  Object.keys(...).map(...).flat is not a function

This command was working until recently.

**Comment by mshanemc** [comment]
what command are you entering?

**Comment by ronyaoun** [comment]
Anything with sfdx shane:mdapi:pull, such as
sfdx shane:mdapi:pull --object=Account -u sandbox

**Comment by mshanemc** [comment]
I'm pretty sure this is nodejs version related.  Any chance you're using <11.15 ?

**Comment by ronyaoun** [comment]
$ node -v
v12.16.1

**Comment by ronyaoun** [comment]
I'll give it a try on another pc, where I know nothing would have changed by network updates.

**Comment by mshanemc** [comment]
I just patched something possibly related by not definitely...be sure to update the plugin

**Comment by mshanemc** [comment]
Can you try `--object Account` (no equals) so it's treated like a flag?

**Comment by mshanemc** [comment]
[both formats work for me, but I'm not sure why]

**Comment by ronyaoun** [comment]
I have uninstalled the SFDX CLI and all it's plugins.  Uninstalled Node.
Installed everything back from scratch, and same issue.

I have also installed the plugin on 4 different workstations and same issue.

$ sfdx -v
sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3

$ node -v
v12.16.1

$ sfdx plugins
shane-sfdx-plugins 4.20.0

**Comment by DebuggingYou** [comment]
Unfortunately I get the same error. 
The command I'm using is the following one: `sfdx shane:mdapi:pull --all -u DEMO:uat`

My current setup and versions are these: 
```
❯ sfdx -v
sfdx-cli/7.50.0-9030e49cbb darwin-x64 node-v10.15.3
```
```
❯ node -v
v12.16.1
```
```
❯ sfdx plugins
shane-sfdx-plugins 4.22.0
```

I tried to figure out if something happens by updating the SFDX plugins, and following warning message was given: 
```
❯ sfdx plugins:update
warning "shane-sfdx-plugins > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".
```

Any help is much appreciated!

**Comment by mshanemc** [comment]
I'm sorry I can't figure out a way to get the error.  

Does it product the same error on **every** type, or just some?

I'm trying to know if there's a specific MD type that's causing a problem, or if it's something environmental with the use of flat().

**Comment by DebuggingYou** [comment]
Hi @mshanemc 

Unfortunately yes, I've tried all options from `sfdx shane:mdapi:pull`
The response is always the same: 
```
❯ sfdx shane:mdapi:pull -t ApexClass -u DEMO:uat
ERROR running shane:mdapi:pull:  Object.keys(...).map(...).flat is not a function
asking your org about its metadata... done
```

**Comment by mshanemc** [comment]
OK, based on looking at your version stuff above, I have an idea what this is and a solution.  

1. you installed sfdx from the package, and it's running node-v10.15.3.  (node 11 is required to get array.flat())
2. which you have, but sfdx isn't using it, maybe?

Solution: uninstall sfdx, and install using the npm approach (scroll down on this page)
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm

I'm sorry about this, and I'm going to whine a bit to the CLI team about this :)

**Comment by DebuggingYou** [comment]
That was the solution! 😃 
Thank you @mshanemc 

In case someone needs also to uninstall SFDX installed from the package, please have a look here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

**Comment by ronyaoun** [comment]
That fixed it.  Thanks Shane.
