### ISSUE TITLE
This plugin is not digitally signed and its authenticity cannot be verified.

### ISSUE THREAD

**Issue by Stwissel** [mshanemc/shane-sfdx-plugins#8]
Love your work. Big stumbling block is the error message:
This plugin is not digitally signed and its authenticity cannot be verified.
Freaks out corporate users.

Any chance to sign the package?

**Comment by mshanemc** [comment]
I don’t think Salesforce supports that yet.  There’s a way for individual machines to whitelist plugins they trust so the message gets skipped.

**Comment by mshanemc** [comment]
I've heard winter20 on 3rd-party plugin signing
